### ISSUE TITLE
USB复合设备不能同时操作各设备

### ISSUE THREAD

**Issue by Barfell** [eclipse-threadx/usbx#155]
手上有块 STM32U5x9J-DK开发板，实现了MSC+CDC+HID, HID自发自收可以，CDC自发自收也可以，MSC读写也可以，但是这三个类型的设备不能同时读写操作，并且MSC写文件后，HID设备无法收数据，就是从电脑端向开发板发数据不能成功，无无法执行到USBD_Custom_HID_SetReport函数位置，但设备向电脑是可以发送数据的。。MSC写文件后，CDC重新打开，收发是没问题的。

**Comment by Barfell** [comment]
已经可以了，在MSC中用HAL_SD_WriteBlocks 替代fx_media_write, 用HAL_SD_ReadBlock 替代 fx_media_read，三种设备可以同时工作。

**Comment by rahmanih** [comment]
>已 经 可 以 了

Closing this as the issue seems to have been solved 😊
