### ISSUE TITLE
Watchdog for USB application thread

### ISSUE THREAD

**Issue by MaJerle** [eclipse-threadx/usbx#96]
**Is your feature request related to a problem? Please describe.**
Use of RTOS commonly involved having software+hardware watchdog to ensure threads are working properly.
When using CDC ACM class, application thread doing read/write operations blocks forever and does not provide a "keep-alive" option to implement watchdog.

**Describe the solution you'd like**
I'd like to have an option to block read/write threads for max time and get error back if it failed to do the operation.
I'd like to have an option for USB core thread to call custom macro (that can be implemented by user) to update "keep alive" status and reset software watchdog.

**Describe alternatives you've considered**
A macro + option for thread timeouts

**Additional context**
None

**Comment by xiaocq2001** [comment]
Thanks for the feedback.

For host, the timeout is defined [here](https://github.com/azure-rtos/usbx/blob/3af3626c9b4b5fefbe4016582b896ad79287df62/common/usbx_host_classes/inc/ux_host_class_cdc_acm.h#L85).

For device, the timeout is changed through ioctl function, e.g.,
```
ux_device_class_cdc_acm_ioctl(cdc_acm, UX_SLAVE_CLASS_CDC_ACM_IOCTL_SET_READ_TIMEOUT, 30/* passed to semephore wait */);
```
